version: '3'
services:
  php:
    build: build/php
    expose:
      - '9000'
    volumes:
      - ./symfony:/var/www/html/symfony:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - "81:80"
    depends_on:
        - php
    volumes:
        - ./symfony:/var/www/html/symfony:cached
        - ./logs:/var/log/nginx
